ERROR 2025-04-19 16:45:51,884 exception Invalid HTTP_HOST header: '0.0.0.0:8000'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '0.0.0.0:8000'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
WARNING 2025-04-19 16:45:52,142 log Bad Request: /
ERROR 2025-04-19 16:47:04,637 exception Invalid HTTP_HOST header: '0.0.0.0:8000'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '0.0.0.0:8000'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
WARNING 2025-04-19 16:47:04,638 log Bad Request: /
ERROR 2025-04-19 16:47:05,840 exception Invalid HTTP_HOST header: '0.0.0.0:8000'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '0.0.0.0:8000'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
WARNING 2025-04-19 16:47:05,842 log Bad Request: /
ERROR 2025-04-19 16:47:20,152 middleware Error en /: home.html
Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/kali/Documentos/Heroku/bank_api/api/views.py", line 13, in get
    return render(request, 'home.html')
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
ERROR 2025-04-19 16:47:20,154 log Internal Server Error: /
Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/kali/Documentos/Heroku/bank_api/api/views.py", line 13, in get
    return render(request, 'home.html')
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader.py", line 61, in render_to_string
    template = get_template(template_name, using=using)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/template/loader.py", line 19, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: home.html
WARNING 2025-04-19 16:48:49,972 log Not Found: /favicon.ico
WARNING 2025-04-19 16:50:49,564 log Not Found: /favicon.ico
WARNING 2025-04-19 16:50:54,150 log Not Found: /favicon.ico
ERROR 2025-04-19 18:31:47,943 exception Invalid HTTP_HOST header: '0.0.0.0:8000'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '0.0.0.0:8000'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
WARNING 2025-04-19 18:31:48,492 log Bad Request: /
ERROR 2025-04-19 18:31:48,571 exception Invalid HTTP_HOST header: '0.0.0.0:8000'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '0.0.0.0:8000'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
WARNING 2025-04-19 18:31:48,573 log Bad Request: /favicon.ico
ERROR 2025-04-19 18:32:39,273 exception Invalid HTTP_HOST header: '0.0.0.0:8000'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
Traceback (most recent call last):
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/utils/deprecation.py", line 119, in __call__
    response = self.process_request(request)
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/middleware/common.py", line 48, in process_request
    host = request.get_host()
  File "/home/kali/Documentos/Heroku/bank_api/.venv/lib/python3.13/site-packages/django/http/request.py", line 186, in get_host
    raise DisallowedHost(msg)
django.core.exceptions.DisallowedHost: Invalid HTTP_HOST header: '0.0.0.0:8000'. You may need to add '0.0.0.0' to ALLOWED_HOSTS.
WARNING 2025-04-19 18:32:39,519 log Bad Request: /
ERROR 2025-04-19 18:33:58,028 log Internal Server Error: /app/sct/initiate/
ERROR 2025-04-19 18:36:28,996 log Internal Server Error: /app/sct/initiate/
WARNING 2025-04-19 20:51:37,757 log Bad Request: /app/sct/initiate/
ERROR 2025-04-19 21:05:15,720 log Internal Server Error: /app/sct/initiate/
ERROR 2025-04-19 21:15:03,866 log Internal Server Error: /app/sct/initiate/
