ERROR 2025-05-06 17:43:52,920 middleware Error en /dashboard/: Reverse for 'send_transfer_viewGPT4' not found. 'send_transfer_viewGPT4' is not a valid view function or pattern name.
Traceback (most recent call last):
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/contrib/auth/decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/markmur88/Documentos/GitHub/api_bank_h2/api/views.py", line 39, in get
    return render(request, 'dashboard.html', {
        'creditors': creditors,
        'transfers': transfers
    })
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/template/defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'send_transfer_viewGPT4' not found. 'send_transfer_viewGPT4' is not a valid view function or pattern name.
ERROR 2025-05-06 17:43:53,155 log Internal Server Error: /dashboard/
Traceback (most recent call last):
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/core/handlers/exception.py", line 55, in inner
    response = get_response(request)
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/views/generic/base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
           ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/utils/decorators.py", line 48, in _wrapper
    return bound_method(*args, **kwargs)
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/contrib/auth/decorators.py", line 59, in _view_wrapper
    return view_func(request, *args, **kwargs)
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/views/generic/base.py", line 143, in dispatch
    return handler(request, *args, **kwargs)
  File "/home/markmur88/Documentos/GitHub/api_bank_h2/api/views.py", line 39, in get
    return render(request, 'dashboard.html', {
        'creditors': creditors,
        'transfers': transfers
    })
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/shortcuts.py", line 25, in render
    content = loader.render_to_string(template_name, context, request, using=using)
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/template/loader.py", line 62, in render_to_string
    return template.render(context, request)
           ~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/template/backends/django.py", line 107, in render
    return self.template.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/template/base.py", line 171, in render
    return self._render(context)
           ~~~~~~~~~~~~^^^^^^^^^
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/template/loader_tags.py", line 159, in render
    return compiled_parent._render(context)
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/test/utils.py", line 114, in instrumented_test_render
    return self.nodelist.render(context)
           ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/template/loader_tags.py", line 65, in render
    result = block.nodelist.render(context)
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/template/base.py", line 1016, in render
    return SafeString("".join([node.render_annotated(context) for node in self]))
                               ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/template/defaulttags.py", line 243, in render
    nodelist.append(node.render_annotated(context))
                    ~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/template/base.py", line 977, in render_annotated
    return self.render(context)
           ~~~~~~~~~~~^^^^^^^^^
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/template/defaulttags.py", line 480, in render
    url = reverse(view_name, args=args, kwargs=kwargs, current_app=current_app)
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/urls/base.py", line 98, in reverse
    resolved_url = resolver._reverse_with_prefix(view, prefix, *args, **kwargs)
  File "/home/markmur88/Documentos/Entorno/venvAPI/lib/python3.13/site-packages/django/urls/resolvers.py", line 831, in _reverse_with_prefix
    raise NoReverseMatch(msg)
django.urls.exceptions.NoReverseMatch: Reverse for 'send_transfer_viewGPT4' not found. 'send_transfer_viewGPT4' is not a valid view function or pattern name.
WARNING 2025-05-06 17:43:53,359 log Not Found: /favicon.ico
